add webcams config files
noi-techpark/it.bz.opendatahub.databrowser pull request #118
Opened 2022-08-12 17:36 UTC by BlueRyse

2022-08-15 10:39 UTC, gappc requested changes

2022-08-15 10:39 UTC, gappc commented on databrowser/src/config/tourism/webcamInfo/webcamInfo.listView.ts
> +export const eventTopicsListView: ListViewConfig = {
Variable name seems wrong - should probably be something like "webcamInfoListView"

2022-08-15 10:39 UTC, gappc commented on databrowser/src/config/tourism/webcamInfo/webcamInfo.views.ts
> +  table: eventTopicsListView,
Please check the variable name (see other comment)

2022-08-16 17:05 UTC, BlueRyse commented
@gappc Lukas fixed the naming issues, can this be merged now?

2022-08-16 17:15 UTC, BlueRyse commented
@gappc Nevermind, I saw the new Webcams listview configuration. Let me implement that and then we can merge.

2022-08-16 19:37 UTC, merged

2022-08-16 19:44 UTC, gappc commented
Hi @BlueRyse, the merge is done, thx for your work.

There is no dedicated Cell Component for URLs at the moment, we could implement one if necessary. I've started a new discussion (see #120), it would be nice if you could add yout use case.