Add page tabs and language picker
noi-techpark/it.bz.opendatahub.databrowser pull request #20
Opened 2021-12-03 08:12 UTC by stplasim

2021-12-03 11:50 UTC, stplasim commented
Hi @mmalfertheiner. I am not sure if this is the best way to define the tab style on `ButtonCustom`. It would give us the advantage of being able to define a primary and secondary. Since there are two styles.

However I am open for suggestions

2021-12-06 08:02 UTC, mmalfertheiner requested changes

2021-12-06 08:02 UTC, mmalfertheiner commented on databrowser/src/components/languageSwitcher/LanguageFilter.vue
> +  </div>
This should be a shareable component. The pagination has the exact same style.

Maybe you can call it `ButtonPillGroup`?

https://getbootstrap.com/docs/4.0/components/button-group/

2021-12-06 08:02 UTC, mmalfertheiner commented on databrowser/src/pages/DatasetDetailPage.vue
> +            :languages="['DE', 'IT', 'EN', 'NL', 'CS', 'PL', 'FR', 'RU']"
I would extract this into a configuration somewhere global.

2021-12-09 10:06 UTC, mmalfertheiner commented
Hi @stplasim,

could you please keep the ButtonPillGroup clean and remove all the mobile dialog logic from the component. For example, the pagination should use the ButtonPillGroup as well, but it behaves different on mobile.

2021-12-09 14:31 UTC, mmalfertheiner requested changes

2021-12-09 14:31 UTC, mmalfertheiner commented on databrowser/src/pages/DatasetDetailPage.vue
>            />
I would wrap this into a `LanguagePicker` component, to reduce the complexity of the DatasetDetailPage.

2021-12-10 12:48 UTC, merged